### ISSUE TITLE
azurerm_postgresql_server validation

### ISSUE THREAD

**Issue by larsmars** [Azure/terraform-azurerm-postgresql#22]
A predefined invalid administrator_login string name should be detected at` terraform validation` step or at lest at `terraform plan` step.

It is now detected at `terraform apply` step.

Predefined:
```
variable "administrator_login_pg1" {
  description = "The Administrator Login for the PostgreSQL Server. Changing this forces a new resource to be created."
  default     = "pg-admin-1"
  type        = string
}
```
Error message:
`Error: creating PostgreSQL Server rg1-psgql-1" (Resource Group "rg1-dev"): postgresql.ServersClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidUserName" Message="'pg-admin-1' is not a valid name because it contains invalid characters."`

hashicorp/azurerm v2.30.0

**Comment by prein** [comment]
Do you happen to know what should the validation regex for this look like?

**Comment by jiaweitao001** [comment]
Hi @larsmars , this issue has been fixed by https://github.com/hashicorp/terraform-provider-azurerm/issues/10726. Thanks!
