### ISSUE TITLE
Support provisioning of read replica

### ISSUE THREAD

**Issue by manuelnucci** [Azure/terraform-azurerm-postgresql#25]
I'd be really helpful to be able to create a read replica alongside main server.

According to the [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_server#create_mode), it's now possible by setting `create_mode = "Replica"`.

I don't fully understand how `creation_source_server_id` is expected to work, maybe using the same `id` the resource has as output?

I hope this feature can be implemented soon.

Keep up the good work! Cheers!

**Comment by yupwei68** [comment]
Hi, thanks for opening this issue. 
We may enhance this feature in the future. But currently I could not give a plan for it. 
You're welcome to contribute to this module by raising a PR as well. 
If you want to open a PR, please add this feature into the test in test/fixture to integrate the test CI and add this feature in example in README.
