### ISSUE TITLE
Release for support of public_network_access_enabled

### ISSUE THREAD

**Issue by mariodavid** [Azure/terraform-azurerm-postgresql#28]
Hi,

https://github.com/Azure/terraform-azurerm-postgresql/pull/26 introduced the ability to set the variable: `public_network_access_enabled`, which is also documented in the README.

Unfortunately, there seems to be no release of this version, it mainly sits in the master branch.
When using the module from the TF registry, it will complain about the attribute not being there.

Can you release the latest master to also contain this new attribute? 

Thanks

**Comment by BorePlusPlus** [comment]
+1

**Comment by jiaweitao001** [comment]
Hi @mariodavid , sorry for the late response. The new version with `public_network_access_enabled` is available now. Thanks!
