### ISSUE TITLE
Feat : lifecycle Meta-Argument with  Optional variables 

### ISSUE THREAD

**Issue by skgandikota** [Azure/terraform-azurerm-postgresql#31]
Problem Statement : 

Module is not restricting/ prompting  user before destroying or recreating

suggested solution: 
we can include lifecycle Meta-Argument  with variables  as  optional parameters , so any user perform accidental delete or due to some external modules database won't recreate and help user in maintaining the data

**Comment by robin-wayve** [comment]
similarly, it would be nice to `ignore_changes` on `storage_mb` when auto-grow is enabled.

**Comment by jiaweitao001** [comment]
Hi @skgandikota @robin-wayve , thanks for your request! Terraform meta-arguments only accept literal values; it would be tricky to do something as you suggested. Appreciate your contributions!
