### ISSUE TITLE
ssl_minimal_tls_version_enforced argument is now needed for azurerm_postgresql_server resource

### ISSUE THREAD

**Issue by DmitryMihailov** [Azure/terraform-azurerm-postgresql#35]
Got an error while using this module. It refers to new argument `ssl_minimal_tls_version_enforced` in `azurerm_postgresql_server` resource which now needs to be set manually to `false`  if `ssl_enforcement_enabled` is set to `false` as well.

```
`ssl_minimal_tls_version_enforced` must be set to `TLSEnforcementDisabled` if `ssl_enforcement_enabled` is set to `false`

with module.hello-world.module.db.azurerm_postgresql_server.server,
on .terraform/modules/hello-world.db/main.tf line 1, in resource "azurerm_postgresql_server" "server":
1: resource "azurerm_postgresql_server" "server" {
```

Fix PR proposal:  https://github.com/Azure/terraform-azurerm-postgresql/pull/34

**Comment by jiaweitao001** [comment]
Thanks for opening this issue! The request fields are available now.
