### ISSUE TITLE
public_network_access_enabled is missing

### ISSUE THREAD

**Issue by ahmedig** [Azure/terraform-azurerm-postgresql#36]
Release version (latest) : 2.1.0

The variable `public_network_access_enabled` is skipped in the variables.tf and in the main.tf file its not set in the postgresql_server instance, even though its there in your github repository. I think you just need to release a new version.

**Comment by jiaweitao001** [comment]
Hi @ahmedig , `public_network_access_enabled` is now available. Thanks!
