### ISSUE TITLE
Dynamic block for threat_detection_policy

### ISSUE THREAD

**Issue by tommygarvin** [Azure/terraform-azurerm-postgresql#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.6.1

### Module Version

3.1.1

### AzureRM Provider Version

3.77.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_server.threat_detection_policy

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "rg-test"
  location = "westus2"
}

module "postgresql" {
  source  = "Azure/postgresql/azurerm"
  version = "3.1.1"

  administrator_login              = "username"
  administrator_password           = "password"
  location                         = azurerm_resource_group.test.location
  resource_group_name              = azurerm_resource_group.test.name
  server_name                      = "psql-test"
}
```

### tfvars variables values

```hcl
N/A
```

### Debug Output/Panic Output

```shell
╷
│ Error: Invalid dynamic for_each value
│
│   on .terraform/modules/postgresql/main.tf line 22, in resource "azurerm_postgresql_server" "server":
│   22:     for_each = var.threat_detection_policy != null ? ["threat_detection_policy"] : []
│
│ Cannot use a list of string value in for_each. An iterable collection
│ is required.
╵
```

### Expected Behaviour

Dynamic block should work

### Actual Behaviour

╷
│ Error: Invalid dynamic for_each value
│
│   on .terraform/modules/postgresql/main.tf line 22, in resource "azurerm_postgresql_server" "server":
│   22:     for_each = var.threat_detection_policy != null ? ["threat_detection_policy"] : []
│
│ Cannot use a list of string value in for_each. An iterable collection is required.
╵

### Steps to Reproduce

1. `terraform plan`

## Problem

variable `threat_detection_policy` is set as `sensitive = true`
https://github.com/Azure/terraform-azurerm-postgresql/blob/53a73cc8be953535fc2b7f2663338650e217dcf0/variables.tf#L142-L157

However, "Sensitive values [...] cannot be used as arguments to `for_each`"
> Sensitive values, such as [sensitive input variables](https://developer.hashicorp.com/terraform/language/values/variables#suppressing-values-in-cli-output), [sensitive outputs](https://developer.hashicorp.com/terraform/language/values/outputs#sensitive-suppressing-values-in-cli-output), or [sensitive resource attributes](https://developer.hashicorp.com/terraform/language/expressions/references#sensitive-resource-attributes), cannot be used as arguments to for_each.
Source: https://developer.hashicorp.com/terraform/language/meta-arguments/for_each#limitations-on-values-used-in-for_each

Therefore, the dynamic block referencing `var.threat_detection_policy` during `for_each` is failing
https://github.com/Azure/terraform-azurerm-postgresql/blob/53a73cc8be953535fc2b7f2663338650e217dcf0/main.tf#L30-L42

## Suggestions

Wrap `var.threat_detection_policy` in `nonsensitive()` like this https://github.com/Azure/terraform-azurerm-postgresql/pull/98

OR

Remove `sensitive = true` from `threat_detection_policy`
https://github.com/Azure/terraform-azurerm-postgresql/blob/53a73cc8be953535fc2b7f2663338650e217dcf0/variables.tf#L156

**Comment by tobimichael96** [comment]
We encountered the same problem as you did and checked your proposed solution. It works like a charm. Thank you for that! :)

Can someone look over the PR and merge that please?

**Comment by weinmann-kay** [comment]
+1 for this issue!

**Comment by segraef** [comment]
@lonegunmanb @Azure/terraform-azure

**Comment by tommygarvin** [comment]
This was addressed via https://github.com/Azure/terraform-azurerm-postgresql/pull/98 which resulted in `3.2.0` of <https://registry.terraform.io/modules/Azure/postgresql/azurerm/latest>
